public class Practica4 extends javax.swing.JFrame {

    /**
     * Creates new form Practica4
     */
    public Practica4() {
        initComponents();
        supIzqRD.setSelected(true);
        todoscb.setSelected(true);
        todoscbActionPerformed(null);
        this.pack();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgroup = new javax.swing.ButtonGroup();
        supDerRB = new javax.swing.JRadioButton();
        InfDerRB = new javax.swing.JRadioButton();
        supIzqRD = new javax.swing.JRadioButton();
        infIzqRB = new javax.swing.JRadioButton();
        rojocb = new javax.swing.JCheckBox();
        verdecb = new javax.swing.JCheckBox();
        azulcb = new javax.swing.JCheckBox();
        todoscb = new javax.swing.JCheckBox();
        myJPanel1 = new myJPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgroup.add(supDerRB);
        supDerRB.setText("Superior Derecha");
        supDerRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supDerRBActionPerformed(evt);
            }
        });

        bgroup.add(InfDerRB);
        InfDerRB.setText("Inferior Derecha");
        InfDerRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfDerRBActionPerformed(evt);
            }
        });

        bgroup.add(supIzqRD);
        supIzqRD.setText("Superior Izquierda");
        supIzqRD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supIzqRDActionPerformed(evt);
            }
        });

        bgroup.add(infIzqRB);
        infIzqRB.setText("Inferior Izquierda");
        infIzqRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infIzqRBActionPerformed(evt);
            }
        });

        rojocb.setText("Canal Rojo");
        rojocb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rojocbActionPerformed(evt);
            }
        });

        verdecb.setText("Canal Verde");
        verdecb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verdecbActionPerformed(evt);
            }
        });

        azulcb.setText("Canal Azul");
        azulcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                azulcbActionPerformed(evt);
            }
        });

        todoscb.setText("Todos");
        todoscb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todoscbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout myJPanel1Layout = new javax.swing.GroupLayout(myJPanel1);
        myJPanel1.setLayout(myJPanel1Layout);
        myJPanel1Layout.setHorizontalGroup(
            myJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        myJPanel1Layout.setVerticalGroup(
            myJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(myJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(infIzqRB)
                            .addComponent(InfDerRB)
                            .addComponent(supIzqRD)
                            .addComponent(supDerRB))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(verdecb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(azulcb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rojocb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(todoscb, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rojocb)
                    .addComponent(supIzqRD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verdecb)
                    .addComponent(supDerRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InfDerRB)
                    .addComponent(azulcb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infIzqRB)
                    .addComponent(todoscb))
                .addGap(18, 18, 18)
                .addComponent(myJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InfDerRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfDerRBActionPerformed
        // TODO add your handling code here:
        myJPanel1.setIconPosition(3);
        repaint();
    }//GEN-LAST:event_InfDerRBActionPerformed

    private void supDerRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supDerRBActionPerformed
        // TODO add your handling code here:
        myJPanel1.setIconPosition(1);
        repaint();
    }//GEN-LAST:event_supDerRBActionPerformed

    private void azulcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_azulcbActionPerformed
        setRGB();
        checkCB();
    }//GEN-LAST:event_azulcbActionPerformed
    private void setRGB(){
        myJPanel1.invertMode(rojocb.isSelected(), verdecb.isSelected(), azulcb.isSelected());
    }
    private void todoscbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todoscbActionPerformed
        // TODO add your handling code here:
        if (todoscb.isSelected()){
            azulcb.setSelected(true);
            rojocb.setSelected(true);
            verdecb.setSelected(true);
        }else{
            azulcb.setSelected(false);
            rojocb.setSelected(false);
            verdecb.setSelected(false);
        }
        setRGB();
    }//GEN-LAST:event_todoscbActionPerformed

    private void rojocbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rojocbActionPerformed
        setRGB();
        checkCB();
    }//GEN-LAST:event_rojocbActionPerformed

    private void verdecbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verdecbActionPerformed
        setRGB();
        checkCB();
    }//GEN-LAST:event_verdecbActionPerformed

    private void supIzqRDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supIzqRDActionPerformed
        // TODO add your handling code here:
        myJPanel1.setIconPosition(0);
        repaint();
    }//GEN-LAST:event_supIzqRDActionPerformed

    private void infIzqRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infIzqRBActionPerformed
        // TODO add your handling code here:
        myJPanel1.setIconPosition(2);
        repaint();
        
    }//GEN-LAST:event_infIzqRBActionPerformed

    private void checkCB(){
        if(!rojocb.isSelected() || !azulcb.isSelected() || !verdecb.isSelected()){
            todoscb.setSelected(false);
        }else{
            todoscb.setSelected(true);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practica4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practica4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practica4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practica4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practica4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton InfDerRB;
    private javax.swing.JCheckBox azulcb;
    private javax.swing.ButtonGroup bgroup;
    private javax.swing.JRadioButton infIzqRB;
    private myJPanel myJPanel1;
    private javax.swing.JCheckBox rojocb;
    private javax.swing.JRadioButton supDerRB;
    private javax.swing.JRadioButton supIzqRD;
    private javax.swing.JCheckBox todoscb;
    private javax.swing.JCheckBox verdecb;
    // End of variables declaration//GEN-END:variables
}
